# Generated by Django 6.0.6 on 2026-07-08 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_ou', models.CharField(blank=True, help_text='Giới hạn theo OU (khớp DN từ AD sync). Để trống = global — dùng được cho mọi máy.', max_length=512)),
                ('secret_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('secret_prefix', models.CharField(blank=True, help_text='Phần đầu secret (không bí mật) để admin nhận diện trong UI/audit', max_length=8)),
                ('expires_at', models.DateTimeField(help_text='Bắt buộc — secret dùng chung phải có hạn ngắn.')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment secret',
                'verbose_name_plural': 'Enrollment secrets',
                'indexes': [models.Index(fields=['ad_ou'], name='agents_enro_ad_ou_727fac_idx')],
            },
        ),
    ]
