# Generated by Django 6.0.6 on 2026-07-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_enrollmentsecret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentsecret',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text="Để trống = không bao giờ tự hết hạn (chỉ dùng khi admin chủ động chọn 'never_expires', ví dụ secret tĩnh đóng cứng vào MSI cài đặt).", null=True),
        ),
    ]
