# Generated by Django 6.0.6 on 2026-07-02 14:00

import apps.packages.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('min_os', models.CharField(blank=True, max_length=128)),
                ('min_ram_gb', models.PositiveIntegerField(default=0)),
                ('min_disk_gb', models.PositiveIntegerField(default=0)),
                ('total_licenses', models.PositiveIntegerField(default=0)),
                ('used_licenses', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=64)),
                ('installer_file', models.FileField(upload_to=apps.packages.models.installer_upload_path)),
                ('installer_type', models.CharField(choices=[('msi', 'Windows Installer (.msi)'), ('exe', 'Executable (.exe)'), ('msu', 'Windows Update (.msu)'), ('msp', 'Patch (.msp)')], max_length=8)),
                ('install_command', models.TextField(blank=True, help_text='Lệnh cài đặt silent. Dùng {file} làm placeholder cho đường dẫn installer trên máy đích.')),
                ('uninstall_command', models.TextField(blank=True)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('file_size', models.BigIntegerField(default=0)),
                ('success_exit_codes', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='packages.package')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('package', 'version')},
            },
        ),
    ]
