# Generated by Django 6.0.6 on 2026-07-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageversion',
            name='installer_type',
            field=models.CharField(choices=[('msi', 'Windows Installer (.msi)'), ('exe', 'Executable (.exe)'), ('msu', 'Windows Update (.msu)'), ('msp', 'Patch (.msp)'), ('msix', 'MSIX/AppX (.msix/.appx)')], max_length=8),
        ),
    ]
