# Generated by Django 6.0.6 on 2026-07-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_packageversion_installer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageversion',
            name='verify_name',
            field=models.CharField(blank=True, help_text="Tên phần mềm để hậu kiểm sau cài (vd 'Firefox'). Trống = không kiểm.", max_length=255),
        ),
    ]
