# Generated by Django 6.0.6 on 2026-07-04 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_packageversion_verify_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='auto_approve_after_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='package',
            name='auto_download',
            field=models.CharField(choices=[('manual', 'Thủ công (admin duyệt)'), ('immediate', 'Duyệt ngay khi tải'), ('automatic', 'Tự duyệt sau N ngày')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='package',
            name='download_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='package',
            name='inventory_name',
            field=models.CharField(blank=True, help_text="Tên phần mềm trong registry để dò máy lỗi thời (vd 'Google Chrome').", max_length=255),
        ),
        migrations.AddField(
            model_name='packageversion',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='packageversion',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packageversion',
            name='download_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='packageversion',
            name='source',
            field=models.CharField(choices=[('upload', 'Upload thủ công'), ('url', 'Tải từ URL')], default='upload', max_length=8),
        ),
        migrations.CreateModel(
            name='PackageDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=1024)),
                ('version_str', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('downloading', 'Đang tải'), ('success', 'Thành công'), ('unchanged', 'Không đổi (đã có)'), ('failed', 'Thất bại')], db_index=True, default='downloading', max_length=16)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('file_size', models.BigIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='packages.package')),
                ('package_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to='packages.packageversion')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
