# Generated by Django 6.0.6 on 2026-07-04 12:01

import django.db.models.deletion
from django.db import migrations, models

# Ba thư mục gốc mặc định của cây Package Library (mirror PDQ Deploy: Packages/Custom
# Packages/Remove Updates). Mọi package hiện có (chưa gắn folder) được gán vào thư mục
# đầu tiên ("Packages") để không "biến mất" khỏi cây khi UI mới ra mắt.
DEFAULT_FOLDERS = ["Packages", "Custom Packages", "Remove Updates"]


def seed_default_folders(apps, schema_editor):
    PackageFolder = apps.get_model("packages", "PackageFolder")
    Package = apps.get_model("packages", "Package")

    folders = {}
    for name in DEFAULT_FOLDERS:
        folder, _ = PackageFolder.objects.get_or_create(name=name, parent=None)
        folders[name] = folder

    Package.objects.filter(folder__isnull=True).update(folder=folders["Packages"])


def noop_reverse(apps, schema_editor):
    # Không xóa folder/gỡ gán khi rollback — tránh mất dữ liệu người dùng đã tự sắp xếp.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_package_auto_approve_after_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='packages.packagefolder')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.AddField(
            model_name='package',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='packages.packagefolder'),
        ),
        migrations.RunPython(seed_default_folders, noop_reverse),
    ]
