# Generated by Django 6.0.6 on 2026-07-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_packagefolder_package_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageversion',
            name='installer_type',
            field=models.CharField(choices=[('msi', 'Windows Installer (.msi)'), ('exe', 'Executable (.exe)'), ('msu', 'Windows Update (.msu)'), ('msp', 'Patch (.msp)'), ('msix', 'MSIX/AppX (.msix/.appx)'), ('zip', 'Archive nhiều file (.zip, tự giải nén)')], max_length=8),
        ),
    ]
