# Generated by Django 6.0.6 on 2026-07-02 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('package_upload', 'Upload package'), ('credential_create', 'Tạo credential'), ('deployment_create', 'Tạo deployment'), ('deployment_trigger', 'Kích hoạt deployment'), ('deployment_cancel', 'Hủy deployment'), ('job_start', 'Bắt đầu job'), ('job_finish', 'Kết thúc job'), ('machine_sync', 'Đồng bộ máy từ AD')], db_index=True, max_length=32)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('machine_hostname', models.CharField(blank=True, max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
