# Generated by Django 6.0.6 on 2026-07-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('package_upload', 'Upload package'), ('package_update', 'Sửa package'), ('package_delete', 'Xóa package'), ('package_version_delete', 'Xóa version'), ('package_fetch', 'Tải version từ URL'), ('package_approve', 'Duyệt version'), ('update_deploy', 'Deploy cập nhật'), ('credential_create', 'Tạo credential'), ('credential_update', 'Sửa credential'), ('credential_delete', 'Xóa credential'), ('deployment_create', 'Tạo deployment'), ('deployment_update', 'Sửa deployment'), ('deployment_delete', 'Xóa deployment'), ('deployment_trigger', 'Kích hoạt deployment'), ('deployment_cancel', 'Hủy deployment'), ('schedule_create', 'Tạo lịch lặp'), ('schedule_update', 'Sửa lịch lặp'), ('schedule_delete', 'Xóa lịch lặp'), ('job_start', 'Bắt đầu job'), ('job_finish', 'Kết thúc job'), ('machine_sync', 'Đồng bộ máy từ AD'), ('catalog_seed', 'Nạp Package Library mẫu')], db_index=True, max_length=32),
        ),
    ]
