# Generated by Django 6.0.6 on 2026-07-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('package_upload', 'Upload package'), ('package_update', 'Sửa package'), ('package_delete', 'Xóa package'), ('package_version_delete', 'Xóa version'), ('package_fetch', 'Tải version từ URL'), ('package_approve', 'Duyệt version'), ('update_deploy', 'Deploy cập nhật'), ('credential_create', 'Tạo credential'), ('credential_update', 'Sửa credential'), ('credential_delete', 'Xóa credential'), ('deployment_create', 'Tạo deployment'), ('deployment_update', 'Sửa deployment'), ('deployment_delete', 'Xóa deployment'), ('deployment_trigger', 'Kích hoạt deployment'), ('deployment_cancel', 'Hủy deployment'), ('schedule_create', 'Tạo lịch lặp'), ('schedule_update', 'Sửa lịch lặp'), ('schedule_delete', 'Xóa lịch lặp'), ('job_start', 'Bắt đầu job'), ('job_finish', 'Kết thúc job'), ('machine_sync', 'Đồng bộ máy từ AD'), ('machine_purge_all', 'Xóa toàn bộ máy'), ('agent_token_issue', 'Cấp token agent'), ('agent_token_revoke', 'Thu hồi token agent'), ('agent_token_auto_revoke_offline', 'Tự thu hồi token agent do máy offline (enroll lại)'), ('agent_enroll', 'Agent tự đăng ký (self-enrollment)'), ('agent_enrollment_secret_create', 'Tạo enrollment secret'), ('agent_enrollment_secret_revoke', 'Thu hồi enrollment secret'), ('machine_connection_mode_update', 'Đổi chế độ kết nối hàng loạt'), ('catalog_seed', 'Nạp Package Library mẫu'), ('user_update', 'Sửa user'), ('user_delete', 'Xóa user')], db_index=True, max_length=32),
        ),
    ]
