# Generated by Django 6.0.6 on 2026-07-02 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deployments', '0001_initial'),
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ'), ('queued', 'Đã vào hàng đợi'), ('running', 'Đang chạy'), ('success', 'Thành công'), ('success_reboot', 'Thành công (cần reboot)'), ('failed', 'Thất bại'), ('skipped', 'Bỏ qua'), ('cancelled', 'Đã hủy')], db_index=True, default='pending', max_length=20)),
                ('current_step', models.CharField(blank=True, choices=[('precheck', 'Kiểm tra trước'), ('copy', 'Copy file'), ('execute', 'Thực thi cài đặt'), ('collect', 'Thu kết quả'), ('cleanup', 'Dọn dẹp'), ('done', 'Xong')], max_length=20)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('output', models.TextField(blank=True)),
                ('error_output', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='deployments.deployment')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='machines.machine')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['deployment', 'status'], name='jobs_job_deploym_427363_idx')],
                'unique_together': {('deployment', 'machine')},
            },
        ),
    ]
