# Generated by Django 6.0.6 on 2026-07-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='current_step',
            field=models.CharField(blank=True, choices=[('precheck', 'Kiểm tra trước'), ('copy', 'Copy file'), ('execute', 'Thực thi cài đặt'), ('collect', 'Thu kết quả'), ('verify', 'Hậu kiểm'), ('cleanup', 'Dọn dẹp'), ('done', 'Xong')], max_length=20),
        ),
    ]
