# Generated by Django 6.0.6 on 2026-07-02 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
        ('machines', '0001_initial'),
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('scheduled', 'Đã lên lịch'), ('running', 'Đang chạy'), ('completed', 'Hoàn thành'), ('completed_errors', 'Hoàn thành (có lỗi)'), ('failed', 'Thất bại'), ('cancelled', 'Đã hủy')], db_index=True, default='draft', max_length=24)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('max_concurrency', models.PositiveIntegerField(default=15)),
                ('retry_limit', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='credentials.deploycredential')),
                ('package_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='packages.packageversion')),
                ('target_machines', models.ManyToManyField(related_name='deployments', to='machines.machine')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
