# Generated by Django 6.0.6 on 2026-07-03 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0001_initial'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='action',
            field=models.CharField(choices=[('install', 'Cài đặt'), ('uninstall', 'Gỡ cài đặt'), ('reboot', 'Khởi động lại'), ('shutdown', 'Tắt máy'), ('inventory', 'Quét phần mềm (inventory)')], db_index=True, default='install', max_length=16),
        ),
        migrations.AddField(
            model_name='deployment',
            name='targeting_rule',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='package_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='packages.packageversion'),
        ),
    ]
