# Generated by Django 6.0.6 on 2026-07-04 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
        ('deployments', '0002_deployment_action_deployment_targeting_rule_and_more'),
        ('machines', '0003_installedsoftware'),
        ('packages', '0004_package_auto_approve_after_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('install', 'Cài đặt'), ('uninstall', 'Gỡ cài đặt'), ('reboot', 'Khởi động lại'), ('shutdown', 'Tắt máy'), ('inventory', 'Quét phần mềm (inventory)')], default='install', max_length=16)),
                ('targeting_rule', models.JSONField(blank=True, null=True)),
                ('max_concurrency', models.PositiveIntegerField(default=15)),
                ('retry_limit', models.PositiveIntegerField(default=1)),
                ('recurrence_type', models.CharField(choices=[('interval', 'Lặp mỗi N phút'), ('weekly', 'Theo ngày trong tuần')], max_length=16)),
                ('interval_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('weekly_days', models.JSONField(blank=True, default=list)),
                ('weekly_time', models.TimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True, help_text='Tắt để tạm dừng lịch mà không phải xóa.')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployment_schedules', to='credentials.deploycredential')),
                ('package_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployment_schedules', to='packages.packageversion')),
                ('target_machines', models.ManyToManyField(related_name='deployment_schedules', to='machines.machine')),
            ],
            options={
                'verbose_name': 'Lịch lặp deployment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deployment',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='deployments.deploymentschedule'),
        ),
    ]
