# Generated by Django 6.0.6 on 2026-07-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeployCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Tên gợi nhớ, VD 'svc_ryandeploy'", max_length=255, unique=True)),
                ('domain', models.CharField(blank=True, help_text="Tên domain NetBIOS, VD 'CORP'", max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password_encrypted', models.TextField(default='', editable=False)),
                ('is_default', models.BooleanField(default=False, help_text='Credential mặc định khi tạo deployment')),
            ],
            options={
                'verbose_name': 'Deploy Credential',
                'ordering': ['name'],
            },
        ),
    ]
