# Generated by Django 6.0.6 on 2026-07-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostname', models.CharField(db_index=True, max_length=255, unique=True)),
                ('fqdn', models.CharField(blank=True, help_text='Fully-qualified domain name', max_length=512)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('os_name', models.CharField(blank=True, max_length=128)),
                ('os_version', models.CharField(blank=True, max_length=64)),
                ('ram_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('disk_free_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('ad_ou', models.CharField(blank=True, help_text='Distinguished Name của OU trong AD', max_length=512)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True, help_text='Cho phép đẩy phần mềm tới máy này')),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='MachineGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('machines', models.ManyToManyField(blank=True, related_name='groups', to='machines.machine')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
