# Generated by Django 6.0.6 on 2026-07-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.CharField(blank=True, help_text='Host hoặc URI, vd: dc01.corp.local hoặc ldaps://dc01.corp.local', max_length=255)),
                ('base_dn', models.CharField(blank=True, help_text='vd: DC=corp,DC=local', max_length=512)),
                ('search_ou', models.CharField(blank=True, help_text='OU giới hạn tìm kiếm (để trống = toàn bộ base_dn)', max_length=512)),
                ('bind_user', models.CharField(blank=True, help_text='vd: CORP\\svc_deploy', max_length=255)),
                ('bind_password_enc', models.TextField(blank=True, help_text='Token Fernet, không hiển thị')),
                ('use_ssl', models.BooleanField(default=False, help_text='LDAPS (cổng 636)')),
                ('enabled', models.BooleanField(default=False, help_text='Dùng cấu hình này thay cho biến môi trường AD_*')),
            ],
            options={
                'verbose_name': 'Cấu hình AD',
                'verbose_name_plural': 'Cấu hình AD',
            },
        ),
    ]
