# Generated by Django 6.0.6 on 2026-07-03 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_adconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=512)),
                ('version', models.CharField(blank=True, max_length=128)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(default='registry', max_length=32)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_software', to='machines.machine')),
            ],
            options={
                'indexes': [models.Index(fields=['machine', 'name'], name='machines_in_machine_9df890_idx')],
                'unique_together': {('machine', 'name', 'version')},
            },
        ),
    ]
