# Generated by Django 6.0.6 on 2026-07-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_installedsoftware'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='agent_version',
            field=models.CharField(blank=True, help_text='Phiên bản agent đang chạy trên máy, do agent tự báo qua heartbeat', max_length=32),
        ),
        migrations.AddField(
            model_name='machine',
            name='connection_mode',
            field=models.CharField(choices=[('smb', 'SMB push (agentless)'), ('agent', 'Agent (outbound HTTPS)')], db_index=True, default='smb', help_text='Kênh vận chuyển khi đẩy job: SMB push (server chủ động) hay Agent (máy tự poll qua HTTPS)', max_length=8),
        ),
    ]
